In [ ]:
 #Q1: Questions on Basic NumPy Array 
import numpy as np

# (a)	Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) 
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("REVERSED ARRAY IS :")
print(reversed_arr)
print()

# (b)	Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two NumPy in-built methods 
arr1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

# Method 1: ravel()
flat1 = arr1.ravel()
print("FLAT1 IS:")
print(flat1)
# Method 2: flatten()
print("FLAT2 IS:")
flat2 = arr1.flatten()
print(flat2)
print()

# (c)	Compare the following numpy arrays: 
# arr1 = np.array([[1, 2], [3, 4]]) arr2 = np.array([[1, 2], [3, 4]]) 
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

are_equal = np.array_equal(arr1, arr2)
print("ARE THEY EQUAL:")
print(are_equal)
print()
 
# (d)	Find the most frequent value and their indice(s) in the following arrays: 	
#i.	x = np.array([1,2,3,4,5,1,2,1,1,1]) 
x = np.array([1,2,3,4,5,1,2,1,1,1]) 
freq_x = np.bincount(x).argmax()
indices_x = np.where(x == freq_x)[0]
print(indices_x)

# ii.	y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
freq_y = np.bincount(y).argmax()
indices_y = np.where(y == freq_y)[0]
print(indices_y)


# (e)	For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find
gfg = np.matrix([[4, 1, 9], [12, 3, 1], [4, 5, 6]])
# i. Sum of all elements
sum_all = gfg.sum()
print("THE SUM OD ALL IS:")
print(sum_all)
print()

# ii.	Sum of all elements row-wise  
sum_row = gfg.sum(axis=1)
print("ROWISE SUM IS:")
print(sum_row)
print()

# iii.	Sum of all elements column-wise 
sum_col = gfg.sum(axis=0)
print("COLUMN WISE SUM IS:")
print(sum_col)
print()

# (f)	For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find 
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])

# i.	Sum of diagonal elements
diagonal = np.trace(n_array)
print("SUM OF DIAGONAL ELEMENTS IS:")
print(diagonal)
print()

# ii.	Eigen values of matrix 
eigen_vals,eigen_vecs = np.linalg.eig(n_array)
print("EIGEN VALUES:")
print(eigen_vals)
print()

# iii.	Eigen vectors of matrix 
print("EIGEN VECTORS:")
print(eigen_vecs)
print()

# iv. Inverse of matrix 
inverse = np.linalg.inv(n_array)
print("INVERSE OF MATRIX IS:")
print(inverse)
print()

# iv. Determinant of matrix 
det = np.linalg.det(n_array)
print("DETERMINANT OF MATRIX IS:")
print(det)
print()

# (g)	Multiply the following matrices and also find covariance between matrices using NumPy: 
# i. p = [[1, 2], [2, 3]] q = [[4, 5], [6, 7]] 
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
product1 = np.dot(p, q)
print("PRODUCT OF THE MATRICES IS:")
print(product1)
cov1 = np.cov(p.T, q.T)
print("COVARIANCE OF THESE TWO MATRICES IS:")
print(cov1)
print()

# # ii. 	p = [[1, 2], [2, 3], [4, 5]] q = [[4, 5, 1], [6, 7, 2]] 
# p = np.array([[1, 2], [2, 3], [4, 5]])
# q = np.array([[4, 5, 1], [6, 7, 2]])
# product2 = np.dot(p, q)
# print("PRODUCT OF THE MATRICES IS:")
# print(product2)
# cov2 = np.cov(p.T, q.T)
# print("COVARIANCE OF THESE TWO MATRICES IS:")
# print(cov2)

# It will not Work as all the input array dimensions except for the concatenation axis must match exactly,You got the error because p.T and q.T had different shapes and could not be combined in np.cov(), it is showing error of not being same dimension.


# (h)	For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]), find inner, outer and cartesian product?
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

inner = np.inner(x, y)
print("INNER PRODUCT IS:")
print(inner)
print()

outer = np.outer(x, y)
print("OUTER PRODUCT IS:")
print(outer)
print()

cartesian = np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2)
print("CARTESIAN PRODUCT IS:")
print(cartesian)


REVERSED ARRAY IS :
[5 4 6 3 2 1]

FLAT1 IS:
[1 2 3 2 4 5 1 2 3]
FLAT2 IS:
[1 2 3 2 4 5 1 2 3]

ARE THEY EQUAL:
True

[0 5 7 8 9]
[0 1 2]
THE SUM OD ALL IS:
45

ROWISE SUM IS:
[[14]
 [16]
 [15]]

COLUMN WISE SUM IS:
[[20  9 16]]

SUM OF DIAGONAL ELEMENTS IS:
176

EIGEN VALUES:
[98.16835147 28.097044   49.73460452]

EIGEN VECTORS:
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]

INVERSE OF MATRIX IS:
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]

DETERMINANT OF MATRIX IS:
137180.0000000001

PRODUCT OF THE MATRICES IS:
[[16 19]
 [26 31]]
COVARIANCE OF THESE TWO MATRICES IS:
[[0.5 0.5 1.  1. ]
 [0.5 0.5 1.  1. ]
 [1.  1.  2.  2. ]
 [1.  1.  2.  2. ]]

INNER PRODUCT IS:
[[17 52]
 [13 62]]

OUTER PRODUCT IS:
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

CARTESIAN PRODUCT

In [18]:
# Q2: Based on NumPy Mathematics and Statistics 

import numpy as np

# (a)	For the array: array = np.array([[1, -2, 3],[-4, 5, -6]]) 
array = np.array([[1, -2, 3], [-4, 5, -6]])

# i.	Find element-wise absolute value 
abs_array = np.abs(array)
print("Absolute value:\n", abs_array)
print()

# ii.	Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each row. 

# FLATTENED ARRAY
flat = array.flatten()
p25 = np.percentile(flat, 25)
p50 = np.percentile(flat, 50)  # or np.median(flat)
p75 = np.percentile(flat, 75)
print("Flattened Percentiles (25th, 50th, 75th):", p25, p50, p75)
print()

# FOR EACH COLUMN
p_col = np.percentile(array, [25, 50, 75], axis=0)
print("Percentiles for each column:\n", p_col)
print()

# FOR EACH ROW
p_row = np.percentile(array, [25, 50, 75], axis=1)
print("Percentiles for each row:\n", p_row)
print()

# iii. Mean, Median and Standard Deviation of flattened array, of each column, and each row

# MEAN , MEDIAN AND STANDARD DEVIATION OF FLATTENED ARRAY IS
print("Flattened Mean:", np.mean(flat))
print("Flattened Median:", np.median(flat))
print("Flattened Std Dev:", np.std(flat))
print()

# MEAN , MEDIAN AND STANDARD DEVIATION OF EACH COLUMN IS
print("Column Mean:", np.mean(array, axis=0))
print("Column Median:", np.median(array, axis=0))
print("Column Std Dev:", np.std(array, axis=0))
print()

# MEAN , MEDIAN AND STANDARD DEVIATION OF EACH ROW IS
print("Row Mean:", np.mean(array, axis=1))
print("Row Median:", np.median(array, axis=1))
print("Row Std Dev:", np.std(array, axis=1))
print()

# (b)	For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling and truncated value, rounded values 
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

print("Floor:", np.floor(a))

print("Ceiling:", np.ceil(a))

print("Truncated:", np.trunc(a))

print("Rounded:", np.round(a))


Absolute value:
 [[1 2 3]
 [4 5 6]]

Flattened Percentiles (25th, 50th, 75th): -3.5 -0.5 2.5

Percentiles for each column:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]

Percentiles for each row:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]

Flattened Mean: -0.5
Flattened Median: -0.5
Flattened Std Dev: 3.8622100754188224

Column Mean: [-1.5  1.5 -1.5]
Column Median: [-1.5  1.5 -1.5]
Column Std Dev: [2.5 3.5 4.5]

Row Mean: [ 0.66666667 -1.66666667]
Row Median: [ 1. -4.]
Row Std Dev: [2.05480467 4.78423336]

Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling: [-1. -1. -0.  1.  2.  2.  3.]
Truncated: [-1. -1. -0.  0.  1.  1.  3.]
Rounded: [-2. -2. -0.  0.  2.  2.  3.]


In [20]:
# Q3: Based on Searching and Sorting 

import numpy as np

# (a)	For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find 
array = np.array([10, 52, 62, 16, 16, 54, 453])

# i.	Sorted array 
sorted_array = np.sort(array)
print("Sorted array:", sorted_array)
print()

# ii.	Indices of sorted array 
sorted_indices = np.argsort(array)
print("Indices of sorted array:", sorted_indices)
print()

# iii.	4 smallest elements 
smallest_4 = np.sort(array)[:4]
print("4 Smallest elements:", smallest_4)
print()

# iv.	5 largest elements 
largest_5 = np.sort(array)[-5:]
print("5 Largest elements:", largest_5)
print()

# (b)	For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find 
array_b = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

# i.	Integer elements only 
integer_elements = array_b[np.equal(np.mod(array_b, 1), 0)]
print("Integer elements only:", integer_elements)
print()

# ii.	Float elements only
float_elements = array_b[np.not_equal(np.mod(array_b, 1), 0)]
print("Float (non-integer) elements only:", float_elements)
print()


Sorted array: [ 10  16  16  52  54  62 453]

Indices of sorted array: [0 3 4 1 5 2 6]

4 Smallest elements: [10 16 16 52]

5 Largest elements: [ 16  52  54  62 453]

Integer elements only: [1. 2. 3. 2.]

Float (non-integer) elements only: [1.2 2.2]



In [ ]:
# Q4:  
# (a)	Write a function named img_to_array(path) that reads an image from a specified path and save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale images) 

import cv2
import numpy as np

def img_to_array(path):
    # Read the image in grayscale
    gray = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    
    if gray is not None:
        print("Grayscale image detected.")
        np.savetxt("grayscale_image.txt", gray, fmt='%d')
        print("Saved as grayscale_image.txt")
        return
    
    # If not grayscale, try reading as color
    color = cv2.imread(path, cv2.IMREAD_COLOR)
    
    if color is not None:
        print("RGB image detected.")
        # Split into R, G, B and save separately
        b, g, r = cv2.split(color)
        np.savetxt("blue_channel.txt", b, fmt='%d')
        np.savetxt("green_channel.txt", g, fmt='%d')
        np.savetxt("red_channel.txt", r, fmt='%d')
        print("Saved as red_channel.txt, green_channel.txt, blue_channel.txt")
        return

    print("Failed to read image. Check the path.")

img_to_array("spiderman.jpg") 
print()

# (b)	Load the saved file into jupyter notebook? 
gray_img = np.loadtxt("grayscale_image.txt", dtype=np.uint8)
print(gray_img)



Grayscale image detected.
Saved as grayscale_image.txt

[[55 56 57 ... 10  9  9]
 [55 56 58 ... 10  9  9]
 [56 57 58 ... 10  9  9]
 ...
 [26 33 43 ... 61 62 69]
 [36 48 66 ... 61 63 70]
 [49 65 84 ... 64 65 69]]
